Models/Medical.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Blessings.Models
{
    public partial class Medical
    {
        [Key]
        [Column("medical_id")]
        public int MedicalId { get; set; }
        [Required]
        [Column("personToContactFirstName")]
        [Display(Name = "Person To Contact FirstName")]
        [StringLength(50)]
        public string PersonToContactFirstName { get; set; }
        [Required]
        [Column("personToContactLastName")]
        [Display(Name = "Person To Contact LastName")]
        [StringLength(50)]
        public string PersonToContactLastName { get; set; }
        [Required]
        [Column("personToContactPhone")]
        [Display(Name = "Person To Contact Phone")]
        [StringLength(10)]
        public string PersonToContactPhone { get; set; }
        [Required]
        [Column("childsDoctorFirstName")]
        [Display(Name = "Child's Doctor Firstname")]
        [StringLength(50)]
        public string ChildsDoctorFirstName { get; set; }
        [Required]
        [Column("childsDoctorLastName")]
        [Display(Name = "Child's Doctor Lastname LastName")]
        [StringLength(50)]
        public string ChildsDoctorLastName { get; set; }
        [Required]
        [Column("childsDoctorPhone")]
        [Display(Name = "Child's Doctor Phone")]
        [StringLength(10)]
        public string ChildsDoctorPhone { get; set; }
        [Required]
        [Column("regularlyUsedHospitalName")]
        [Display(Name = "Regularly Used Hospital Name")]
        [StringLength(50)]
        public string RegularlyUsedHospitalName { get; set; }
        [Column("diaetryRestriction")]
        [Display(Name = "Diaetry Restriction")]
        [StringLength(100)]
        public string DiaetryRestriction { get; set; }
        [Column("medicalIssue")]
        [Display(Name = "Medical Issue")]
        [StringLength(100)]
        public string MedicalIssue { get; set; }
        [Column("child_id")]
        public int ChildId { get; set; }

        [ForeignKey(nameof(ChildId))]
        [InverseProperty("Medical")]
        public virtual Child Child { get; set; }
    }
}

Controllers/MedicalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Blessings.Models;
using Microsoft.AspNetCore.Authorization;

namespace Blessings.Controllers
{
    /*[Authorize(Roles = "Administrator")]*/
    [Authorize]
    public class MedicalsController : Controller
    {
        private readonly BlessingsdbContext _context;

        public MedicalsController(BlessingsdbContext context)
        {
            _context = context;
        }

        // GET: Medicals
        public async Task<IActionResult> Index()
        {
            var blessingsdbContext = _context.Medical.Include(m => m.Child);
            return View(await blessingsdbContext.ToListAsync());
        }

        // GET: Medicals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medical = await _context.Medical
                .Include(m => m.Child)
                .FirstOrDefaultAsync(m => m.MedicalId == id);
            if (medical == null)
            {
                return NotFound();
            }

            return View(medical);
        }

        // GET: Medicals/Create
        public IActionResult Create(int ChildId)
        {
            var children = from c in _context.Child where c.ChildId == ChildId select c;
            ViewData["ChildId"] = new SelectList(children, "ChildId", "ChildFirstName");
            return View();
        }

        // POST: Medicals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedicalId,PersonToContactFirstName,PersonToContactLastName,PersonToContactPhone,ChildsDoctorFirstName,ChildsDoctorLastName,ChildsDoctorPhone,RegularlyUsedHospitalName,DiaetryRestriction,MedicalIssue,ChildId")] Medical medical)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medical);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Children", new { id = medical.ChildId });
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", medical.ChildId);
            return View(medical);
        }

        // GET: Medicals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medical = await _context.Medical.FindAsync(id);
            if (medical == null)
            {
                return NotFound();
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", medical.ChildId);
            return View(medical);
        }

        // POST: Medicals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedicalId,PersonToContactFirstName,PersonToContactLastName,PersonToContactPhone,ChildsDoctorFirstName,ChildsDoctorLastName,ChildsDoctorPhone,RegularlyUsedHospitalName,DiaetryRestriction,MedicalIssue,ChildId")] Medical medical)
        {
            if (id != medical.MedicalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medical);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicalExists(medical.MedicalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Children", new { id = medical.ChildId });
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", medical.ChildId);
            return View(medical);
        }

        // GET: Medicals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medical = await _context.Medical
                .Include(m => m.Child)
                .FirstOrDefaultAsync(m => m.MedicalId == id);
            if (medical == null)
            {
                return NotFound();
            }

            return View(medical);
        }

        // POST: Medicals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medical = await _context.Medical.FindAsync(id);
            _context.Medical.Remove(medical);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Children", new { id = medical.ChildId });
        }

        private bool MedicalExists(int id)
        {
            return _context.Medical.Any(e => e.MedicalId == id);
        }
    }
}

Views/Medicals/Create.cshtml
@model Blessings.Models.Medical

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/xxjapp/xdialog@3/xdialog.min.css" />
<script src="https://cdn.jsdelivr.net/gh/xxjapp/xdialog@3/xdialog.min.js"></script>

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
            window.onload = function () {
                xdialog.alert("@ViewBag.Message");
            };
    </script>
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">


                    <div class="card-title">
                        <h4>Medical Info</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="Medicals" asp-action="Create" method="post">
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="PersonToContactFirstName" class="control-label"></label>
                                            <input asp-for="PersonToContactFirstName" class="form-control" />
                                            <span asp-validation-for="PersonToContactFirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PersonToContactLastName" class="control-label"></label>
                                            <input asp-for="PersonToContactLastName" class="form-control" />
                                            <span asp-validation-for="PersonToContactLastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PersonToContactPhone" class="control-label"></label>
                                            <input asp-for="PersonToContactPhone" class="form-control" />
                                            <span asp-validation-for="PersonToContactPhone" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorFirstName" class="control-label"></label>
                                            <input asp-for="ChildsDoctorFirstName" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorFirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorLastName" class="control-label"></label>
                                            <input asp-for="ChildsDoctorLastName" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorLastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorPhone" class="control-label"></label>
                                            <input asp-for="ChildsDoctorPhone" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorPhone" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="RegularlyUsedHospitalName" class="control-label"></label>
                                            <input asp-for="RegularlyUsedHospitalName" class="form-control" />
                                            <span asp-validation-for="RegularlyUsedHospitalName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="DiaetryRestriction" class="control-label"></label>
                                            <input asp-for="DiaetryRestriction" class="form-control" />
                                            <span asp-validation-for="DiaetryRestriction" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="MedicalIssue" class="control-label"></label>
                                            <input asp-for="MedicalIssue" class="form-control" />
                                            <span asp-validation-for="MedicalIssue" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildId" class="control-label"></label>
                                            <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" value="Create" class="btn btn-success"> Save Changes </button>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*    End PAge Content *@
    </div>
</div>




@*<h1>Create</h1>

    <h4>Medical</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PersonToContactFirstName" class="control-label"></label>
                    <input asp-for="PersonToContactFirstName" class="form-control" />
                    <span asp-validation-for="PersonToContactFirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PersonToContactLastName" class="control-label"></label>
                    <input asp-for="PersonToContactLastName" class="form-control" />
                    <span asp-validation-for="PersonToContactLastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PersonToContactPhone" class="control-label"></label>
                    <input asp-for="PersonToContactPhone" class="form-control" />
                    <span asp-validation-for="PersonToContactPhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildsDoctorFirstName" class="control-label"></label>
                    <input asp-for="ChildsDoctorFirstName" class="form-control" />
                    <span asp-validation-for="ChildsDoctorFirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildsDoctorLastName" class="control-label"></label>
                    <input asp-for="ChildsDoctorLastName" class="form-control" />
                    <span asp-validation-for="ChildsDoctorLastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildsDoctorPhone" class="control-label"></label>
                    <input asp-for="ChildsDoctorPhone" class="form-control" />
                    <span asp-validation-for="ChildsDoctorPhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RegularlyUsedHospitalName" class="control-label"></label>
                    <input asp-for="RegularlyUsedHospitalName" class="form-control" />
                    <span asp-validation-for="RegularlyUsedHospitalName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DiaetryRestriction" class="control-label"></label>
                    <input asp-for="DiaetryRestriction" class="form-control" />
                    <span asp-validation-for="DiaetryRestriction" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MedicalIssue" class="control-label"></label>
                    <input asp-for="MedicalIssue" class="form-control" />
                    <span asp-validation-for="MedicalIssue" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildId" class="control-label"></label>
                    <select asp-for="ChildId" class ="form-control" asp-items="ViewBag.ChildId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

Views/Medicals/Details.cshtml
@model Blessings.Models.Medical

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Medical</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonToContactFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonToContactFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonToContactLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonToContactLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonToContactPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonToContactPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChildsDoctorFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChildsDoctorFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChildsDoctorLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChildsDoctorLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChildsDoctorPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChildsDoctorPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegularlyUsedHospitalName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegularlyUsedHospitalName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaetryRestriction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaetryRestriction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MedicalIssue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MedicalIssue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Child)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Child.ChildFirstName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MedicalId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Medicals/Edit.cshtml
@model Blessings.Models.Medical

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Edit Medical Info</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="Medicals" asp-action="Edit" method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input asp-for="MedicalId" type="hidden" />
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="PersonToContactFirstName" class="control-label"></label>
                                            <input asp-for="PersonToContactFirstName" class="form-control" />
                                            <span asp-validation-for="PersonToContactFirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PersonToContactLastName" class="control-label"></label>
                                            <input asp-for="PersonToContactLastName" class="form-control" />
                                            <span asp-validation-for="PersonToContactLastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PersonToContactPhone" class="control-label"></label>
                                            <input asp-for="PersonToContactPhone" class="form-control" />
                                            <span asp-validation-for="PersonToContactPhone" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorFirstName" class="control-label"></label>
                                            <input asp-for="ChildsDoctorFirstName" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorFirstName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorLastName" class="control-label"></label>
                                            <input asp-for="ChildsDoctorLastName" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorLastName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildsDoctorPhone" class="control-label"></label>
                                            <input asp-for="ChildsDoctorPhone" class="form-control" />
                                            <span asp-validation-for="ChildsDoctorPhone" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="RegularlyUsedHospitalName" class="control-label"></label>
                                            <input asp-for="RegularlyUsedHospitalName" class="form-control" />
                                            <span asp-validation-for="RegularlyUsedHospitalName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="DiaetryRestriction" class="control-label"></label>
                                            <input asp-for="DiaetryRestriction" class="form-control" />
                                            <span asp-validation-for="DiaetryRestriction" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="MedicalIssue" class="control-label"></label>
                                            <input asp-for="MedicalIssue" class="form-control" />
                                            <span asp-validation-for="MedicalIssue" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildId" class="control-label"></label>
                                            <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                            <span asp-validation-for="ChildId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success"> Update Changes </button>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@*<h1>Edit</h1>

<h4>Medical</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MedicalId" />
            <div class="form-group">
                <label asp-for="PersonToContactFirstName" class="control-label"></label>
                <input asp-for="PersonToContactFirstName" class="form-control" />
                <span asp-validation-for="PersonToContactFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonToContactLastName" class="control-label"></label>
                <input asp-for="PersonToContactLastName" class="form-control" />
                <span asp-validation-for="PersonToContactLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonToContactPhone" class="control-label"></label>
                <input asp-for="PersonToContactPhone" class="form-control" />
                <span asp-validation-for="PersonToContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildsDoctorFirstName" class="control-label"></label>
                <input asp-for="ChildsDoctorFirstName" class="form-control" />
                <span asp-validation-for="ChildsDoctorFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildsDoctorLastName" class="control-label"></label>
                <input asp-for="ChildsDoctorLastName" class="form-control" />
                <span asp-validation-for="ChildsDoctorLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildsDoctorPhone" class="control-label"></label>
                <input asp-for="ChildsDoctorPhone" class="form-control" />
                <span asp-validation-for="ChildsDoctorPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegularlyUsedHospitalName" class="control-label"></label>
                <input asp-for="RegularlyUsedHospitalName" class="form-control" />
                <span asp-validation-for="RegularlyUsedHospitalName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaetryRestriction" class="control-label"></label>
                <input asp-for="DiaetryRestriction" class="form-control" />
                <span asp-validation-for="DiaetryRestriction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicalIssue" class="control-label"></label>
                <input asp-for="MedicalIssue" class="form-control" />
                <span asp-validation-for="MedicalIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildId" class="control-label"></label>
                <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                <span asp-validation-for="ChildId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@