Models/ChildLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Blessings.Models
{
    public class ChildLog
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ChildlogId { get; set; }
        [DataType(DataType.Date)]
        public DateTime Day { get; set; }
        [DataType(DataType.Time)]
        public DateTime? CheckIn { get; set; }
        [DataType(DataType.Time)]
        public DateTime? CheckOut { get; set; }

       
        public int ChildId { get; set; }

        [ForeignKey(nameof(ChildId))]
        [InverseProperty("ChildLog")]
        public virtual Child Child { get; set; }
    }
}

Controllers/ChildLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Blessings.Models;
using Microsoft.AspNetCore.Authorization;

namespace Blessings.Controllers
{
    /* [Authorize(Roles = "Administrator")]*/
    [Authorize]
    public class ChildLogsController : Controller
    {
        private readonly BlessingsdbContext _context;

        public ChildLogsController(BlessingsdbContext context)
        {
            _context = context;
        }

        // GET: ChildLogs
        public async Task<IActionResult> Index()
        {
            var blessingsdbContext = _context.ChildLog.Include(c => c.Child);
            return View(await blessingsdbContext.ToListAsync());
        }

        // GET: ChildLogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var childLog = await _context.ChildLog
                .Include(c => c.Child)
                .FirstOrDefaultAsync(m => m.ChildlogId == id);
            if (childLog == null)
            {
                return NotFound();
            }

            return View(childLog);
        }

        // GET: ChildLogs/Create
        public IActionResult Create()
        {
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName");
            return View();
        }

        // POST: ChildLogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChildlogId,Day,CheckIn,CheckOut,ChildId")] ChildLog childLog)
        {
            if (ModelState.IsValid)
            {
           /*     ChildLog cl = new ChildLog();
                cl.IsAbsent = childLog.IsAbsent;*/
                _context.Add(childLog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", childLog.ChildId);
            return View(childLog);
        }

        // GET: ChildLogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var childLog = await _context.ChildLog.FindAsync(id);
            if (childLog == null)
            {
                return NotFound();
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", childLog.ChildId);
            return View(childLog);
        }

        // POST: ChildLogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChildlogId,Day,CheckIn,CheckOut,ChildId")] ChildLog childLog)
        {
            if (id != childLog.ChildlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(childLog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChildLogExists(childLog.ChildlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", childLog.ChildId);
            return View(childLog);
        }

        // GET: ChildLogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var childLog = await _context.ChildLog
                .Include(c => c.Child)
                .FirstOrDefaultAsync(m => m.ChildlogId == id);
            if (childLog == null)
            {
                return NotFound();
            }

            return View(childLog);
        }

        // POST: ChildLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var childLog = await _context.ChildLog.FindAsync(id);
            _context.ChildLog.Remove(childLog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChildLogExists(int id)
        {
            return _context.ChildLog.Any(e => e.ChildlogId == id);
        }
    }
}

Views/ChildLogs/Create.cshtml
@model Blessings.Models.ChildLog

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">


                    <div class="card-title">
                        <h4>Add ChildLog info</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="ChildLogs" asp-action="Create" method="post">
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                     
                                            <div class="form-group">
                                                <label asp-for="Day" class="control-label"></label>
                                                <input asp-for="Day" class="form-control" />
                                                <span asp-validation-for="Day" class="text-danger"></span>
                                            </div>

                                            <div class="form-group">
                                                <label asp-for="CheckIn" class="control-label"></label>
                                                <input asp-for="CheckIn" class="form-control" />
                                                <span asp-validation-for="CheckIn" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="CheckOut" class="control-label"></label>
                                                <input asp-for="CheckOut" class="form-control" />
                                                <span asp-validation-for="CheckOut" class="text-danger"></span>
                                            </div>

                                            <div class="form-group">
                                                <label asp-for="ChildId" class="control-label"></label>
                                                <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" value="Create" class="btn btn-success"> Save Changes </button>
                                            </div>
                                            <div>
                                                <a asp-action="Index">Back to List</a>
                                            </div>
                                        </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @* End PAge Content *@
    </div>
</div>







@*<h1>Create</h1>

    <h4>ChildLog</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Day" class="control-label"></label>
                    <input asp-for="Day" class="form-control" />
                    <span asp-validation-for="Day" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CheckIn" class="control-label"></label>
                    <input asp-for="CheckIn" class="form-control" />
                    <span asp-validation-for="CheckIn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CheckOut" class="control-label"></label>
                    <input asp-for="CheckOut" class="form-control" />
                    <span asp-validation-for="CheckOut" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildId" class="control-label"></label>
                    <select asp-for="ChildId" class ="form-control" asp-items="ViewBag.ChildId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

Views/ChildLogs/Delete.cshtml
@model Blessings.Models.ChildLog

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Are you sure you want to delete this?</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">

                            <div class="col-lg-8">
                                <div>
                                    <hr />
                                    <dl class="row">
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.Day)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.Day)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.CheckIn)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.CheckIn)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.CheckOut)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.CheckOut)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.Child)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.Child.ChildFirstName)
                                        </dd>
                                    </dl>

                                    <form asp-action="Delete">
                                        <input type="hidden" asp-for="ChildlogId" />
                                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                                        <a asp-action="Index">Back to List</a>
                                    </form>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>

@*<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChildLog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckOut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Child)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Child.ChildFirstName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ChildlogId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>*@

Views/ChildLogs/Details.cshtml
@model Blessings.Models.ChildLog

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div></div>
                    <div class="card-body">
                        <h4 class="card-title">ChildLog Details</h4>
                        <div class="table-responsive m-t-40">
                        </div>
                        <div>
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Day)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Day)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CheckIn)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CheckIn)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CheckOut)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CheckOut)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Child)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Child.ChildFirstName)
                                </dd>
                            </dl>
                        </div>
                        <div>
                            <a asp-action="Edit" asp-route-id="@Model.ChildlogId">Edit</a> |
                            <a asp-action="Index">Back to List</a>
                        </div>


                    </div>
                </div>
            </div>
        </div>

        <!-- End PAge Content -->
    </div>
</div>


@*<h1>Details</h1>

    <div>
        <h4>ChildLog</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Day)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Day)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CheckIn)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CheckIn)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CheckOut)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CheckOut)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Child)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Child.ChildFirstName)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ChildlogId">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

Views/ChildLogs/Edit.cshtml
@model Blessings.Models.ChildLog

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Edit ChildLog Info</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="ChildLogs" asp-action="Edit" method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input asp-for="ChildlogId" type="hidden" />
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="Day" class="control-label"></label>
                                            <input asp-for="Day" class="form-control" />
                                            <span asp-validation-for="Day" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="CheckIn" class="control-label"></label>
                                            <input asp-for="CheckIn" class="form-control" />
                                            <span asp-validation-for="CheckIn" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="CheckOut" class="control-label"></label>
                                            <input asp-for="CheckOut" class="form-control" />
                                            <span asp-validation-for="CheckOut" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildId" class="control-label"></label>
                                            <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                            <span asp-validation-for="ChildId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success"> Update Changes </button>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>




@*<h1>Edit</h1>

<h4>ChildLog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ChildlogId" />
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildId" class="control-label"></label>
                <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                <span asp-validation-for="ChildId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

Views/ChildLogs/Index.cshtml
@model IEnumerable<Blessings.Models.ChildLog>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="form-group">
                        <a value="Create" href="@Url.Action("Create", "ChildLogs")" class="btn btn-success"> Create Child Log </a>
                    </div>
                    @*<form asp-controller="ChildLogs" asp-action="Index" method="get">
                        <p>
                            Search:
                            <input type="text" name="SearchString">

                        </p>
                    </form>*@
                    <div class="card-body">
                        <h4 class="card-title">Child Log List</h4>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover  table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Child)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Day)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.CheckIn)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.CheckOut)
                                        </th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Child.ChildFirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Day)
                                        </td>

                                        <td>
                                            @if (item.CheckIn != null)
                                            {
                                                @Html.DisplayFor(modelItem => item.CheckIn)
                                            }
                                            else
                                            {
                                                <label class="label btn-danger">Absent</label>
                                            }
                                        </td>
                                        <td>

                                            @if (item.CheckOut != null)
                                            {
                                                @Html.DisplayFor(modelItem => item.CheckOut)
                                            }
                                            else
                                            {
                                                <label class="label btn-danger">Absent</label>
                                            }
                                        </td>

                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.ChildlogId" class="btn btn-icon btn-warning btn-xs m-b-5">
                                                <i class="fa fa-edit"></i>Edit
                                            </a> |
                                            <a asp-action="Details" asp-route-id="@item.ChildlogId" class="btn btn-icon btn-success btn-xs m-b-5">
                                                <i class="fa fa-edit"></i>Details
                                            </a> |
                                            <a asp-action="Delete" asp-route-id="@item.ChildlogId" class="btn btn-icon btn-danger btn-xs m-b-5">
                                                <i class="fa fa-remove"></i>Delete
                                            </a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @* End PAge Content *@
    </div>
</div>

@*<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Child)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Child.ChildFirstName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ChildlogId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ChildlogId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ChildlogId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@