Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Blessings.Models
{
    public partial class Payment
    {
        [Key]
        [Column("payment_id")]
        public int PaymentId { get; set; }
        [Required]
        [Column("payerName")]
        [StringLength(50)]
        public string PayerName { get; set; }
        [Required]
        [Column("paymentType")]
        [StringLength(50)]
        public string PaymentType { get; set; }
        [Column("amount")]
        public float Amount { get; set; }
        [Column("paymentDate", TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime PaymentDate { get; set; }
        [Required]
        [Display(Name = "Status")]
        [StringLength(25)]
        public string Status { get; set; }
        [Column("child_id")]
        public int ChildId { get; set; }

        [ForeignKey(nameof(ChildId))]
        [InverseProperty("Payment")]
        public virtual Child Child { get; set; }
        
        [Column("EnrollmentId")]
        public int? EnrollmentId { get; set; }

        [ForeignKey(nameof(EnrollmentId))]
        [InverseProperty("Payment")]
        public virtual Enrollment Enrollment { get; set; }
    }
}

Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Blessings.Models;
using Blessings.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace Blessings.Controllers
{
    /*[Authorize(Roles = "Administrator")]*/
    [Authorize]
    public class PaymentsController : Controller
    {
        private readonly BlessingsdbContext _context;

        public PaymentsController(BlessingsdbContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var blessingsdbContext = _context.Payment.Include(p => p.Child);
            return View(await blessingsdbContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment
                .Include(p => p.Child)
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create(int ChildId)
        {
            var children = from c in _context.Child
                           join e in _context.Enrollment on c.ChildId equals e.ChildId
                           select c;
            ViewData["ChildId"] = new SelectList(children, "ChildId", "ChildFirstName");

            /*    var coursefee = from cf in _context.CourseFees join e in _context.Enrollment on cf.Course equals e.Course select cf.Fee;
                double amount = Convert.ToDouble(coursefee);
                ViewData["Amount"] = new SelectList(amount, "ChildId", "ChildLastName");*/
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId,PayerName,PaymentType,Amount,PaymentDate,Status,ChildId")] Payment payment)
        {
        if (ModelState.IsValid)
        {
                var coursefee = from c in _context.Child
                                join e in _context.Enrollment on payment.ChildId equals e.ChildId 
                                join cf in _context.CourseFees on e.Course equals cf.Course
                                select cf.Fee;

           payment.Amount = Convert.ToInt32(coursefee.First());
            _context.Add(payment);
           await _context.SaveChangesAsync();

           
           return RedirectToAction("Details", "Children", new { id = payment.ChildId });
        }
            var children = from c in _context.EnrollmentViewModel where c.ChildId == payment.ChildId select c;
            ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", payment.ChildId);
        return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
        if (id == null)
        {
           return NotFound();
        }

        var payment = await _context.Payment.FindAsync(id);
        if (payment == null)
        {
           return NotFound();
        }
        ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", payment.ChildId);
        return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentId,PayerName,PaymentType,Amount,PaymentDate,ChildId")] Payment payment)
        {
        if (id != payment.PaymentId)
        {
           return NotFound();
        }

        if (ModelState.IsValid)
        {
           try
           {
               _context.Update(payment);
               await _context.SaveChangesAsync();
           }
           catch (DbUpdateConcurrencyException)
           {
               if (!PaymentExists(payment.PaymentId))
               {
                   return NotFound();
               }
               else
               {
                   throw;
               }
           }
           return RedirectToAction("Details", "Children", new { id = payment.ChildId });
        }
        ViewData["ChildId"] = new SelectList(_context.Child, "ChildId", "ChildFirstName", payment.ChildId);
        return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
        if (id == null)
        {
           return NotFound();
        }

        var payment = await _context.Payment
           .Include(p => p.Child)
           .FirstOrDefaultAsync(m => m.PaymentId == id);
        if (payment == null)
        {
           return NotFound();
        }

        return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
        var payment = await _context.Payment.FindAsync(id);
        _context.Payment.Remove(payment);
        await _context.SaveChangesAsync();
        return RedirectToAction("Details", "Children", new { id = payment.ChildId });
        }

        private bool PaymentExists(int id)
        {
        return _context.Payment.Any(e => e.PaymentId == id);
        }
        }
        }

Views/Payments/Create.cshtml
@model Blessings.Models.Payment

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
            window.onload = function () {
                xdialog.alert("@ViewBag.Message");
            };
    </script>
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">


                    <div class="card-title">
                        <h4>Add payment info</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="Payments" asp-action="Create" method="post">
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="PayerName" class="control-label"></label>
                                            <input asp-for="PayerName" class="form-control" />
                                            <span asp-validation-for="PayerName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PaymentType" class="control-label"></label>
                                            <input asp-for="PaymentType" class="form-control" />
                                            <span asp-validation-for="PaymentType" class="text-danger"></span>
                                        </div>
                                        
                                        <div class="form-group">
                                                <label asp-for="PaymentDate" class="control-label"></label>
                                                <input asp-for="PaymentDate" class="form-control" />
                                                <span asp-validation-for="PaymentDate" class="text-danger"></span>
                                         </div>
                                         <div class="form-group">
                                                <label asp-for="Status" class="control-label"></label>
                                                <input asp-for="Status" class="form-control" />
                                                <span asp-validation-for="Status" class="text-danger"></span>
                                          </div>
                                         <div class="form-group">
                                                <label asp-for="ChildId" class="control-label"></label>
                                                <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                          </div>
                                         <div class="form-group">
                                                <button type="submit" value="Create" class="btn btn-success"> Save Changes </button>
                                         </div>

                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               @* End PAge Content *@
        </div>
    </div>






    @*<div class="reportHeader">
        <h1>
            Create
        </h1>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PayerName" class="control-label"></label>
                    <input asp-for="PayerName" class="form-control" />
                    <span asp-validation-for="PayerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaymentType" class="control-label"></label>
                    <input asp-for="PaymentType" class="form-control" />
                    <span asp-validation-for="PaymentType" class="text-danger"></span>
                </div>
                                        
                                          <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
                <div class="form-group">
                    <label asp-for="PaymentDate" class="control-label"></label>
                    <input asp-for="PaymentDate" class="form-control" />
                    <span asp-validation-for="PaymentDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChildId" class="control-label"></label>
                    <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <input type="button" class="button" value="Back to List"
               onclick="location.href='@Url.Action("Index")'" />
    </div>*@

    @*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

Views/Payments/Delete.cshtml
@model Blessings.Models.Payment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Are you sure you want to delete this?</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">

                            <div class="col-lg-8">
                                <div>
                                    <hr />
                                    <dl class="row">
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.PayerName)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.PayerName)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.PaymentType)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentType)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.Amount)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.Amount)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.PaymentDate)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentDate)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.Status)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.Status)
                                        </dd>
                                        <dt class="col-sm-2">
                                            @Html.DisplayNameFor(model => model.Child)
                                        </dt>
                                        <dd class="col-sm-10">
                                            @Html.DisplayFor(model => model.Child.ChildFirstName)
                                        </dd>
                                    </dl>
                                    <form asp-action="Delete">
                                        <input type="hidden" asp-for="PaymentId" />
                                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                                        <input type="button" class="button" value="Children List"
                                               onclick="location.href='@Url.Action("Index", "Children")'" />
                                    </form>

                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>




@*<div class="reportHeader">
    <h3>
        Are you sure you want to delete this?
    </h3>
    </div>
    <div>
        <h4>Payment</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PayerName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PayerName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentType)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Child)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Child.ChildFirstName)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="PaymentId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <input type="button" class="button" value="Children List"
                   onclick="location.href='@Url.Action("Index", "Children")'" />
        </form>
    </div>*@

Views/Payments/Details.cshtml
@model Blessings.Models.Payment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div></div>
                    <div class="card-body">
                        <h4 class="card-title">Payment Details</h4>
                        <div class="table-responsive m-t-40">
                        </div>
                        <div>
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.PayerName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.PayerName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.PaymentType)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.PaymentType)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Amount)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Amount)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.PaymentDate)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.PaymentDate)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Status)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Status)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Child)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Child.ChildFirstName)
                                </dd>
                            </dl>
                        </div>

                                       

                        

                    </div>
                </div>
            </div>
        </div>

        <!-- End PAge Content -->
    </div>
</div>








@*<div class="reportHeader">
        <h3>
            Payment details
        </h3>
    </div>


    <div>
        <h4>Payment</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PayerName)
            </dt>
            <dd class="col-sm-10">
               @Html.DisplayFor(model => model.PayerName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentType)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Child)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Child.ChildFirstName)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.PaymentId">Edit</a> |
        <input type="button" class="button" value="Children List"
               onclick="location.href='@Url.Action("Index", "Children")'" />
    </div>*@

Views/Payments/Edit.cshtml
@model Blessings.Models.Payment

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Edit Medical Info</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="Payments" asp-action="Edit" method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input asp-for="PaymentId" type="hidden" />
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="PayerName" class="control-label"></label>
                                            <input asp-for="PayerName" class="form-control" />
                                            <span asp-validation-for="PayerName" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PaymentType" class="control-label"></label>
                                            <input asp-for="PaymentType" class="form-control" />
                                            <span asp-validation-for="PaymentType" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Amount" class="control-label"></label>
                                            <input asp-for="Amount" class="form-control" />
                                            <span asp-validation-for="Amount" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="PaymentDate" class="control-label"></label>
                                            <input asp-for="PaymentDate" class="form-control" />
                                            <span asp-validation-for="PaymentDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Status" class="control-label"></label>
                                            <input asp-for="Status" class="form-control" />
                                            <span asp-validation-for="Status" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ChildId" class="control-label"></label>
                                            <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                                            <span asp-validation-for="ChildId" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success"> Update Changes </button>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>





@*<div class="reportHeader">
    <h3>
        Edit Payment info
    </h3>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaymentId" />
            <div class="form-group">
                <label asp-for="PayerName" class="control-label"></label>
                <input asp-for="PayerName" class="form-control" />
                <span asp-validation-for="PayerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildId" class="control-label"></label>
                <select asp-for="ChildId" class="form-control" asp-items="ViewBag.ChildId"></select>
                <span asp-validation-for="ChildId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <input type="button" class="button" value="Children List"
           onclick="location.href='@Url.Action("Index", "Children")'" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@